@startuml CartDiagram
start
#lightgreen:User clicks Cart Icon;
#lightyellow:Load Cart Items;

#lightyellow:if (Cart is Empty?) then (Yes)
    #lightyellow:Show "Your cart is empty";
    #lightyellow:Display Back Button;
    #lightblue:if (Click Back?) then (Yes)
        #lightgreen:Redirect to Home Page;
        stop
    endif
else (No)
    #lightyellow:Display Cart Items with Checkboxes;
    #lightyellow:Show "Back" and "Checkout" Buttons;
    endif
    repeat :View Cart;
        fork
        #lightblue:if (User selects items?) then (Yes)
            #lightblue:if (Clicks "Checkout Selected"?) then (Yes)
                #lightgreen:Proceed to Checkout Page;
                stop
            endif
        endif
        fork again
        #lightblue:if (Clicks "Back"?) then (Yes)
            #lightgreen:Redirect to Home Page;
            stop
        endif
        end fork
    repeat while (User observes items?) is (yes)

@enduml