@startuml OrdersHistoryDiagram
start
#lightgreen:Orders List Page;
repeat :View Orders;
fork
#lightyellow:if (Order Status) then(Processing)
  #lightblue:if(User clicks Cancel) then(Yes)
    #lightyellow:Confirm Cancellation?;
    #lightblue:if (Confirmed) then (Yes)
      #lightyellow:Order Cancelled;
    else (No)
      #lightgreen:Return to Orders List;
      stop
    endif
  endif
else (Not Processing)
  #lightyellow:Cancel disabled\n(Status not "Processing");
endif
fork again
#lightblue:if(Clicked Back) then(yes)
  #lightgreen:Redirect to\nPrevious Page;
  stop
endif
end fork
repeat while(still viewing) is(yes)
@enduml