@startuml AdminNewItemDiagram
skinparam activity {
    BackgroundColor<<repeat>> #f8d7da
    BorderColor<<repeat>> #a94442
    FontColor<<repeat>> black
}
start
#lightgreen:Admin Add New Item Page;

repeat :Edit Item;
  
  fork
    #lightblue:if (Admin Changes a field?) then (yes)
      #Lightyellow:Updated;
    endif
  fork again
    #lightblue:if (Admin Clicks Back?) then (yes)
      #lightgreen:Redirect to Previous Page;
      stop
    endif
  end fork

repeat while (Not Created)

#LightBlue:Admin Clicks Create Item;
  repeat
  #LightYellow:System Attempts Create;
  #lightyellow:if (Added Successful?) then (yes)
    #LightGreen:Redirect to Admin Dashboard;
    stop
  else (no)
    #red:Show "Creation Failed" Alert;
    end
  endif
repeat while (Retry?)
@enduml