@startuml HomeDiagram
start
#lightgreen:User's Home Page;

repeat
    #lightyellow:Display Items with:\n- Add to Wishlist buttons\n- View buttons\n- Search/Sort options\n- Cart/Wishlist/Orders icons;
    fork
    #lightblue:if (View Item\nClicked) then (yes)
        #lightyellow:Click "View" on item;
        #lightgreen:Redirect to Item Page;
        stop
    endif
    fork again
    #lightblue:if (Search/Sort) then (Yes)
        #lightblue:Enters search query or selects sort;
        #lightyellow:Update displayed items;
    endif
    fork again
    #lightblue:if (Add to Wishlist) then (Yes)
        #lightyellow:Add item to Wishlist;
        #lightyellow:Show confirmation;
    endif
    fork again
    #lightblue:if (Click Cart Icon) then (Yes)
        #lightgreen:Redirect to Cart Page;
        stop
    endif
    fork again
    #lightblue:if (Click Wishlist) then (Yes)
        #lightgreen:Redirect to Wishlist Page;
        stop
    endif
    fork again
    #lightblue:if (Click Orders) then (Yes)
        #lightgreen:Redirect to Orders History;
        stop
    endif
    fork again
    #lightblue:if (Click Logout) then (Yes)
        #lightyellow:Logout user;
        #lightgreen:Redirect to Landing Page;
        stop
    endif
    end fork
repeat while (Continue Browsing?) is (Yes)
@enduml