@startuml ItemByIdDiagram
start
#lightgreen:Item Page;
#lightyellow:Display Item Information;

repeat
    fork
        #lightblue:if (User Adjust quantity?) then (yes)
            #lightblue:Click + or -;
            #lightyellow:Update quantity display;
        endif
    fork again
        #lightblue:if (Click "Add to Cart") then (Yes)
        #lightyellow:Add (Item × Quantity) to Cart;
        #lightyellow:if (Item in Wishlist?) then (Yes)
            #lightyellow:Remove from Wishlist;
            #lightyellow:Update Wishlist;
        endif
        #lightyellow:Show "Added to Cart" confirmation;
        endif
    fork again
        #lightblue:if (Click "Back") then (Yes)
        #lightgreen:Redirect to Previous Page;
        stop
        endif
    end fork
repeat while (User continues interacting?) is (Yes)
@enduml