@startuml ItemByIdDiagram
start
:Item Page;
:Display Item Information;

repeat
    fork
        if (User Adjust quantity?) then (yes)
            :Click + or -;
            :Update quantity display;
        endif
    fork again
        if (Click "Add to Cart") then (Yes)
        :Add (Item × Quantity) to Cart;
        if (Item in Wishlist?) then (Yes)
            :Remove from Wishlist;
            :Update Wishlist;
        endif
        :Show "Added to Cart" confirmation;
        endif
    fork again
        if (Click "Back") then (Yes)
        :Redirect to Previous Page;
        stop
        endif
    end fork
repeat while (User continues interacting?) is (Yes)
@enduml