@startuml RegisterDiagram
start
#lightgreen:Reigster Page;
repeat :Create Credentials;
fork
  #lightblue:if (User clicks Back?) then (yes)
    #lightgreen:Redirect to\nPrevious Page;
    stop
  endif
fork again
  #lightblue:if (User submits credentials?) then (yes)
    #lightyellow:System checks Auth;
    #lightyellow:if (Auth Successful?) then (yes)
      #lightgreen:System: Redirect to\nHome Page;
      stop
    else
      #orange:Auth Failed - Show error;
      
    endif
  endif
  end fork
repeat while (not submitted)

@enduml


