name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOCKER_ENV: true
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Install Mockoon CLI
        run: npm install -g @mockoon/cli

      - name: Start Mockoon
        run: |
          mockoon-cli start --data ./mockoon.json --port 4000 &
          sleep 5

      - name: Wait for Mockoon to be ready
        run: |
          for i in {1..10}; do
            curl --silent -X POST http://localhost:4000/pay \
              -H "Content-Type: application/json" \
              -d '{"amount":1}' && break
            echo "Waiting for Mockoon..."
            sleep 2
          done

      - name: Build Next.js app
        run: npm run build

      - name: Start Next.js server
        run: npm run start &

      # - name: Wait for dev server
      #   run: npx wait-on http://localhost:3000
      
      - name: Buffer before tests
        run: sleep 10

      - name: Inject .env.docker for Playwright
        run: |
          echo "BASE_URL=http://web:3000" >> .env.docker
          echo "CHAT_URL=http://chat:3001/chat" >> .env.docker
          echo "MOCKOON_URL=http://mockoon:4000" >> .env.docker
          echo "NEXT_PUBLIC_MOCKOON_URL=http://mockoon:4000" >> .env.docker

      - name: Run Playwright tests
        run: npx playwright test
        #continue-on-error: true

      - name: List test results
        run: ls -la ./allure-results

      - name: Generate Allure report
        run: npx allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report